// generate-advisor-summary.ts — produces a 1-page markdown summary for advisor handoff.
// Reuses the download pattern from download-brief.ts.

import type { AnalysisReportData } from '../components/chat-cards/types'

function formatDollar(amount: number): string {
  const sign = amount >= 0 ? '+' : '-'
  return `${sign}$${Math.abs(Math.round(amount)).toLocaleString()}`
}

export function generateAdvisorSummary(report: AnalysisReportData): string {
  const { signal, verdict, impactDelta } = report
  const netImpact = impactDelta.netImpactMidCad
  const date = new Date().toISOString().slice(0, 10)

  const lines: string[] = [
    `# Signal Analysis Summary`,
    '',
    `**Signal:** ${signal.headline}`,
    `**Date:** ${date}`,
    `**Estimated 1-Month Impact:** ${formatDollar(netImpact)}`,
    `**Confidence:** ${report.qualityScore}%`,
    `**Agents Used:** ${report.agentCount}`,
    '',
    '---',
    '',
    '## Top Affected Holdings',
    '',
  ]

  const top = impactDelta.affectedHoldings.slice(0, 5)
  for (const h of top) {
    lines.push(`- **${h.ticker}** (${h.name}): ${formatDollar(h.impactMidCad)}`)
  }
  if (impactDelta.affectedHoldings.length > 5) {
    lines.push(`- +${impactDelta.affectedHoldings.length - 5} more holdings`)
  }
  lines.push('')

  // Recommendations
  if (verdict.recommendations.length > 0) {
    lines.push('## Recommendations', '')
    for (const rec of verdict.recommendations) {
      const baseline = rec.isDoNothing ? ' *(baseline)*' : ''
      lines.push(`### ${rec.title}${baseline}`)
      lines.push('')
      lines.push(rec.description)
      lines.push(`- **Estimated Cost:** ${rec.estimatedCost}`)
      lines.push(`- **Risk Reduction:** ${rec.riskReduction}`)
      lines.push('')
    }
  }

  // Key assumptions from debate
  if (report.intermediateArtifacts?.debateResolution) {
    const debate = report.intermediateArtifacts.debateResolution
    lines.push('## Key Assumptions', '')
    lines.push(`- Debate resolved **${debate.consensusDirection}** after ${debate.rounds} rounds`)
    if (debate.unresolvedDisagreements.length > 0) {
      lines.push('- Unresolved disagreements:')
      for (const d of debate.unresolvedDisagreements) {
        lines.push(`  - ${d}`)
      }
    }
    lines.push('')
  }

  lines.push(
    '---',
    '',
    '*This analysis is for informational purposes only. Past performance does not guarantee future results. Consult a qualified financial advisor before making investment decisions.*',
    '',
    `*Generated by Prism Intelligence on ${date}*`,
  )

  return lines.join('\n')
}

export function downloadAdvisorSummary(report: AnalysisReportData): void {
  const markdown = generateAdvisorSummary(report)
  const blob = new Blob([markdown], { type: 'text/markdown' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = `advisor-summary-${report.signal.id}-${new Date().toISOString().slice(0, 10)}.md`
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}
