// Research Brief — pure template formatting engine.
// Assembles all pipeline artifacts into a structured, auditable research brief.
// No LLM calls — just formatting computed data and agent outputs.

import type {
  Signal,
  FundManagerVerdict,
  DebateResolution,
  RiskChallenge,
  StressTestResult,
  JudgeVerdict,
  ResearchBrief,
  ResearchBriefSection,
  DollarRange,
} from '@prism/shared'

const DISCLAIMER =
  'This research brief is generated by an AI system for informational purposes only. ' +
  'It does not constitute financial advice, a recommendation, or an offer to buy or sell securities. ' +
  'Past performance and model outputs do not guarantee future results. ' +
  'Always consult a qualified financial advisor before making investment decisions.'

// ── Section Builders ────────────────────────────────────────

function buildCausalAnalysis(
  verdict: FundManagerVerdict,
  debate: DebateResolution,
): ResearchBriefSection {
  const directionLabel = debate.consensusDirection === 'negative' ? 'bearish'
    : debate.consensusDirection === 'positive' ? 'bullish'
      : debate.consensusDirection === 'mixed' ? 'mixed' : 'neutral'

  const holdingChains = verdict.holdingImpacts
    .filter((h) => h.derivation && h.derivation.length > 0)
    .map((h) => {
      const arrow = h.direction > 0 ? '↑' : h.direction < 0 ? '↓' : '→'
      return `- **${h.ticker}** (${h.name}) ${arrow}: ${h.derivation}`
    })

  const debatePoints = debate.debateTranscript
    .filter((arg) => arg.keyPoints.length > 0)
    .flatMap((arg) => arg.keyPoints.slice(0, 2))
    .slice(0, 6)

  const unresolvedSection = debate.unresolvedDisagreements.length > 0
    ? [
        '',
        '**Unresolved Causal Uncertainties:**',
        ...debate.unresolvedDisagreements.map((d) => `- ${d}`),
      ]
    : []

  const lines = [
    `**Overall Direction:** ${directionLabel} (confidence: ${(debate.consensusConfidence * 100).toFixed(0)}%)`,
    '',
    '**Signal → Portfolio Transmission:**',
    ...holdingChains,
    '',
    '**Key Causal Arguments (from debate):**',
    ...(debatePoints.length > 0
      ? debatePoints.map((p) => `- ${p}`)
      : ['- See debate summary for full transcript.']),
    ...unresolvedSection,
  ]

  return { title: 'Causal Analysis', content: lines.join('\n') }
}

function buildSignalSummary(signal: Signal): ResearchBriefSection {
  const sourceList = signal.sources.length > 0
    ? signal.sources.map((s) => s.title).join(', ')
    : 'Gemini Search grounding'

  return {
    title: 'Signal Summary',
    content: [
      `**Signal:** ${signal.headline}`,
      `**Description:** ${signal.description}`,
      `**Sources:** ${sourceList}`,
      `**Urgency:** ${signal.urgency}`,
      `**Sentiment:** ${signal.sentiment}`,
      `**Affected Exposures:** ${signal.affectedExposures.join(', ')}`,
      signal.portfolioSummary ? `**Portfolio Impact:** ${signal.portfolioSummary}` : '',
    ].filter(Boolean).join('\n'),
  }
}

function buildDebateSummary(debate: DebateResolution): ResearchBriefSection {
  const lines = [
    `**Rounds:** ${debate.rounds}`,
    `**Consensus Direction:** ${debate.consensusDirection}`,
    `**Consensus Magnitude:** ${(debate.consensusMagnitude * 100).toFixed(0)}%`,
    `**Consensus Confidence:** ${(debate.consensusConfidence * 100).toFixed(0)}%`,
    '',
    '**Bull Concessions:**',
    ...(debate.bullConcessions.length > 0
      ? debate.bullConcessions.map((c) => `- ${c}`)
      : ['- None']),
    '',
    '**Bear Concessions:**',
    ...(debate.bearConcessions.length > 0
      ? debate.bearConcessions.map((c) => `- ${c}`)
      : ['- None']),
    '',
    '**Unresolved Disagreements:**',
    ...(debate.unresolvedDisagreements.length > 0
      ? debate.unresolvedDisagreements.map((d) => `- ${d}`)
      : ['- None']),
  ]

  return { title: 'Debate Summary', content: lines.join('\n') }
}

function buildRiskAssessment(risk: RiskChallenge): ResearchBriefSection {
  const lines = [
    `**Assumptions Challenged:** ${risk.challengedAssumptions.length}`,
    `**Confidence Adjustment:** ${(risk.recommendedConfidenceAdjustment * 100).toFixed(0)}%`,
    `**Assessment:** ${risk.overallAssessment}`,
    '',
    '**Key Challenges:**',
    ...risk.challengedAssumptions.map((c) =>
      `- [${c.analystType}] "${c.assumption}" — Counter: ${c.counterEvidence} (${(c.likelihoodOfBeingWrong * 100).toFixed(0)}% likely wrong)`,
    ),
  ]

  return { title: 'Risk Assessment', content: lines.join('\n') }
}

function formatDollarRange(range: DollarRange): string {
  const fmt = (n: number) => `$${Math.abs(n).toLocaleString()}`
  const sign = range.mid < 0 ? '-' : '+'
  return `${sign}${fmt(range.low)} to ${sign}${fmt(range.high)} (mid: ${sign}${fmt(range.mid)})`
}

function buildStressScenarios(stress: StressTestResult): ResearchBriefSection {
  const lines = [
    `**Simulations:** ${stress.numSimulations.toLocaleString()}`,
    `**Reversal Probability:** ${(stress.reversalProbability * 100).toFixed(1)}%`,
    '',
    '| Scenario | Low | Mid | High |',
    '|----------|-----|-----|------|',
    `| Base Case | $${stress.baseCase.low.toLocaleString()} | $${stress.baseCase.mid.toLocaleString()} | $${stress.baseCase.high.toLocaleString()} |`,
    `| Downside (5th %ile) | $${stress.downside.low.toLocaleString()} | $${stress.downside.mid.toLocaleString()} | $${stress.downside.high.toLocaleString()} |`,
    `| Tail Risk (1st %ile) | $${stress.tailRisk.low.toLocaleString()} | $${stress.tailRisk.mid.toLocaleString()} | $${stress.tailRisk.high.toLocaleString()} |`,
  ]

  return { title: 'Stress Scenarios', content: lines.join('\n') }
}

function buildCalibratedImpact(verdict: FundManagerVerdict): ResearchBriefSection {
  const lines = [
    '| Ticker | Value (CAD) | Direction | 1M Impact | Confidence | Derivation |',
    '|--------|-------------|-----------|-----------|------------|------------|',
    ...verdict.holdingImpacts.map((h) => {
      const impact1M = h.impact['1M']
      const impactStr = impact1M ? formatDollarRange(impact1M) : 'N/A'
      return `| ${h.ticker} | $${h.holdingValueCad.toLocaleString()} | ${h.direction > 0 ? '↑' : h.direction < 0 ? '↓' : '→'} ${h.direction.toFixed(2)} | ${impactStr} | ${(h.confidence * 100).toFixed(0)}% | ${h.derivation} |`
    }),
  ]

  return { title: 'Calibrated Impact', content: lines.join('\n') }
}

function buildRecommendations(verdict: FundManagerVerdict): ResearchBriefSection {
  const lines = verdict.recommendations.map((rec) => [
    `### ${rec.title}${rec.isDoNothing ? ' (Baseline)' : ''}`,
    rec.description,
    `**Estimated Cost:** ${rec.estimatedCost}`,
    `**Risk Reduction:** ${rec.riskReduction}`,
    `**Trade-offs:** ${rec.tradeoffs.join('; ')}`,
  ].join('\n'))

  return { title: 'Recommendations', content: lines.join('\n\n') }
}

function buildPerspectives(verdict: FundManagerVerdict): ResearchBriefSection {
  const lines = [
    '**Bull Case:**',
    verdict.perspectiveBreakdown.bullCase,
    '',
    '**Bear Case:**',
    verdict.perspectiveBreakdown.bearCase,
    '',
    '**Unresolved:**',
    ...(verdict.perspectiveBreakdown.unresolvedDisagreements.length > 0
      ? verdict.perspectiveBreakdown.unresolvedDisagreements.map((d) => `- ${d}`)
      : ['- None']),
  ]

  return { title: 'Perspective Breakdown', content: lines.join('\n') }
}

function buildQualityAssessment(judge: JudgeVerdict): ResearchBriefSection {
  const lines = [
    `**Overall Quality:** ${(judge.overallQualityScore * 100).toFixed(0)}%`,
    `**Convergence:** ${judge.convergenceReached ? 'Yes' : 'No'}`,
    '',
    '| Dimension | Score |',
    '|-----------|-------|',
    `| Evidence Grounding | ${(judge.evidenceGrounding * 100).toFixed(0)}% |`,
    `| Assumption Quality | ${(judge.assumptionQuality * 100).toFixed(0)}% |`,
    `| Magnitude Calibration | ${(judge.magnitudeCalibration * 100).toFixed(0)}% |`,
    `| Internal Consistency | ${(judge.internalConsistency * 100).toFixed(0)}% |`,
    `| Completeness | ${(judge.completeness * 100).toFixed(0)}% |`,
    judge.feedback ? `\n**Feedback:** ${judge.feedback}` : '',
  ].filter(Boolean)

  return { title: 'Quality Assessment', content: lines.join('\n') }
}

function buildRiskAdjustments(verdict: FundManagerVerdict): ResearchBriefSection {
  const lines = [
    `**Confidence Haircut:** ${(verdict.riskAdjustments.confidenceHaircut * 100).toFixed(0)}%`,
    `**Scenario Preference:** ${verdict.riskAdjustments.scenarioPreference}`,
    '',
    '**Magnitude Bounds Applied:**',
    ...(verdict.riskAdjustments.magnitudeBoundsApplied.length > 0
      ? verdict.riskAdjustments.magnitudeBoundsApplied.map((b) => `- ${b}`)
      : ['- None']),
  ]

  return { title: 'Risk Adjustments', content: lines.join('\n') }
}

// ── Collect All Sources ─────────────────────────────────────
function collectSources(
  debate: DebateResolution,
  risk: RiskChallenge,
): { index: number; description: string }[] {
  const allSources = new Set<string>()

  // From debate transcript
  for (const arg of debate.debateTranscript) {
    for (const ev of arg.evidenceCited) {
      allSources.add(ev)
    }
  }

  // From risk challenge
  for (const challenged of risk.challengedAssumptions) {
    allSources.add(challenged.counterEvidence)
  }

  return [...allSources].map((desc, i) => ({
    index: i + 1,
    description: desc,
  }))
}

// ── Main: Generate Research Brief ───────────────────────────
export function generateResearchBrief(params: {
  readonly signal: Signal
  readonly verdict: FundManagerVerdict
  readonly debateResolution: DebateResolution
  readonly riskChallenge: RiskChallenge
  readonly stressTest: StressTestResult
  readonly judgeVerdict: JudgeVerdict
}): ResearchBrief {
  const { signal, verdict, debateResolution, riskChallenge, stressTest, judgeVerdict } = params

  const sections: ResearchBriefSection[] = [
    buildSignalSummary(signal),
    buildCausalAnalysis(verdict, debateResolution),
    buildDebateSummary(debateResolution),
    buildRiskAssessment(riskChallenge),
    buildStressScenarios(stressTest),
    buildCalibratedImpact(verdict),
    buildRiskAdjustments(verdict),
    buildPerspectives(verdict),
    buildRecommendations(verdict),
    buildQualityAssessment(judgeVerdict),
    { title: 'Sources', content: collectSources(debateResolution, riskChallenge)
      .map((s) => `[${s.index}] ${s.description}`)
      .join('\n') || 'No sources cited.' },
  ]

  const fullText = sections
    .map((s) => `## ${s.title}\n\n${s.content}`)
    .join('\n\n---\n\n')

  // Compute overall impact range from verdict
  const impacts1M = verdict.holdingImpacts
    .map((h) => h.impact['1M'])
    .filter((r): r is DollarRange => r != null)

  const impactRange: DollarRange = impacts1M.length > 0
    ? {
        low: impacts1M.reduce((sum, r) => sum + r.low, 0),
        mid: impacts1M.reduce((sum, r) => sum + r.mid, 0),
        high: impacts1M.reduce((sum, r) => sum + r.high, 0),
      }
    : { low: 0, mid: 0, high: 0 }

  const sources = collectSources(debateResolution, riskChallenge)

  return {
    signalId: signal.id,
    generatedAt: new Date().toISOString(),
    qualityScore: judgeVerdict.overallQualityScore,
    impactRange,
    sections,
    sources,
    fullText,
    disclaimer: DISCLAIMER,
  }
}
